spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://927rc2cw6945.vicp.fun:25936/dcdb
    username: dc
    password: 12345

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.edu.bjfu.dualchoice.pojo
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 8090